compressionLevel: 0

defaultSemverRangePrefix: ''

enableGlobalCache: true

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: node-modules

npmAuthToken: ${ABERLAAS_RELEASE_NPM_AUTH_TOKEN:-}
