#!/usr/bin/env bash
set -e

# Specifically run lint:root if we run it from root
scripts=(lint:direct)
[[ "$INIT_CWD" == "$(pwd)" ]] && scripts+=(lint:root)

yarn g:turbo run "${scripts[@]}" --continue "$@"
