#!/usr/bin/env bash
set -e

if [[ $npm_execpath = *"yarn"* ]]; then
  echo "This script must be run using npm, not yarn.";
  exit 1
fi

version=$(npm view ./ version)
echo "Current version is $version"
read -p "New version: " new_version

release-it --no-npm.publish "$new_version"
npm publish
