#!/usr/bin/env bash
# shellcheck disable=2154
set -e

# When running `yarn run`, the special var $npm_execpath is set. We check it to
# stop the execution as there is a bug in the `yarn release` process that
# prevent releasing. npm release should be used instead.
if [[ $npm_execpath = *"yarn"* ]]; then
  echo "This script must be run using npm, not yarn.";
  exit 1
fi

version=$(node -p -e "require('./package.json').version")
echo "Current version is $version"
read -rp "New version: " new_version

release-it --no-npm.publish "$new_version"
npm publish
